services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ageri-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      # nÃ£o exponha 4317/4318 do Jaeger no host pra evitar conflito com o collector
    networks:
      - ageri
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.140.0
    container_name: ageri-otel-collector
    command: ["--config=/etc/otelcol-contrib/otel-collector.yml"]
    volumes:
      - ./otel-collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml:ro
    ports:
      - "14317:4317"    # OTLP gRPC (host->collector)
      - "14318:4318"    # OTLP HTTP (host->collector)
      - "8889:8889"     # Prometheus scrape endpoint
      - "13133:13133"   # Health check
    depends_on:
      - jaeger
    networks:
      - ageri
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: ageri-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - ageri
    restart: unless-stopped

  server-api:
    build: ./server-api
    container_name: ageri-server-api
    environment:
      - OTEL_SERVICE_NAME=server-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOG_LEVEL=INFO
      - EXTERNAL_USERS_URL=https://jsonplaceholder.typicode.com/users
    ports:
      - "18081:8000"
    depends_on:
      - otel-collector
    networks:
      - ageri
    restart: unless-stopped

  client-api:
    build: ./client-api
    container_name: ageri-client-api
    environment:
      - OTEL_SERVICE_NAME=client-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOG_LEVEL=INFO
      - SERVER_API_URL=http://server-api:8000
    ports:
      - "18080:8000"
    depends_on:
      - server-api
    networks:
      - ageri
    restart: unless-stopped

networks:
  ageri:
    name: ageri
